### ISSUE TITLE
Missing files when auto-updating libraries

### ISSUE THREAD

**Issue by polyrhythmatic** [processing/p5.js-editor#102]
Running the get audio sources example code 

https://github.com/processing/p5.js-sound/blob/master/examples/select_audioIn_source/test.js

with the p5 editor and I'm getting this error from p5.js

"p5.js:3661 Uncaught Error: [object Arguments]is not a valid color representation."

I thought I had this example running fine in the desktop IDE not long ago - as did @therewasaguy 

I don't think this is an audio related issue and @antiboredom seems to agree it could be an editor issue.

I've tried running the latest p5-sound and p5.js builds as well as removing all fill() and background() statements to try and eliminate variables.

**Comment by antiboredom** [comment]
Hey - this is definitely an issue with the editor. Fix coming soon!
