### ISSUE TITLE
Error on create new empty project

### ISSUE THREAD

**Issue by nucliweb** [processing/p5.js-editor#103]
Hi,

in the current version 0.3.0, I can't create new empty project, because the files in node_assets/p5/empty_project/llibraries/p5.js & p5.sound.js don't have the code of file.

![](https://s3-eu-west-1.amazonaws.com/nucliweb/P5js/P5-Editor.gif)

**Comment by antiboredom** [comment]
Hi - yeah there's some regression with the auto-updating feature - looking into it!

**Comment by lmccart** [comment]
where are you autoupdating from? this could be caused by the removal of the libs from the p5.js repo. i've switched over the website to read the package.json for the version then download from cdnjs.
https://github.com/processing/p5.js-website/blob/master/download/release.php#L60

**Comment by antiboredom** [comment]
Yeah - it was looking for the files in the wrong place. I've just uploaded a new release that should fix the issue.

@lmccart this brings up another question for me: do we want the editor to continue to automatically update to new releases of p5? Or should we couple releases of the editor with releases of the library?

**Comment by nucliweb** [comment]
@antiboredom the notification of a new version, redirect to Page not found :(

https://github.com/processing/p5.js-editor/releases/download/v0.3.1/p5.zip

**Comment by nucliweb** [comment]
Mmmm... the name of file it's p5.app.zip ;)

**Comment by antiboredom** [comment]
@nucliweb oops!! fixed now.

**Comment by nucliweb** [comment]
:+1:
