### ISSUE TITLE
static mode

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-editor#104]
I can't find an issue discussing this so thought I would note one here.  (Apologies if I'm just out of the loop.)

Is implementing support for quick "static" sketches on our radar / something we want to implement?  I have always used Processing's static mode for teaching and find it nice to avoid the whole `setup()` and `draw()` thing the first week.  This would be something (as with the Processing PDE) only available in the IDE itself (desktop or web) as behind the scenes magic would be needed.

Example sketch:

```javascript
createCanvas(100, 100);
background(0);
stroke(255);
line(0, 0, 100, 100);
```

Current the error (as expected) is: `1: Uncaught ReferenceError: createCanvas is not defined`

**Comment by brysonian** [comment]
I was wondering the same thing. Somehow I thought that static mode was supported by the lib but maybe it was removed?

**Comment by antiboredom** [comment]
hey @shiffman thanks for bringing this up - I think I should be able to get this working. Static mode is effectively the same as just evaluating code in setup but not draw, correct?

**Comment by antiboredom** [comment]
@shiffman - decided to take a crack at it. I added a check for window.setup and window.draw - if neither exists it'll grab the user's code and then eval it inside a setup function. Can give it a look and let me know if it's what you had in mind?

here's the branch:
https://github.com/processing/p5.js-editor/tree/static-mode

and here's a build:
http://saaaam.s3.amazonaws.com/p5.app.zip

**Comment by shiffman** [comment]
@antiboredom yup, this works perfectly.

@brysonian I recall a discussion a long time ago with @lmccart about static mode, it was there at some point and I think maybe it was removed b/c it was overly complicated to implement/maintain for any native environment?  Gosh, I have a terrible memory.

With the IDE, as @antiboredom has done, I think it's worth having in there?  Although is that a problem if it only works in the IDE and then you can't post your code?  I guess the "export" feature in the IDE would take care of that by adding `setup()`?

**Comment by brysonian** [comment]
Yeah this is perfect, thanks @antiboredom! Just in time to record a class tomorrow. I guess it is a little concerning that it doesn't work outside of the IDE. But short of adding an export feature or making this part of the core i'm not sure how to handle it. Perhaps (and maybe this is a good idea anyway) we should throw an error if no setup function is found? That might be ab opportunity to put some messaging about static mode being IDE only.

**Comment by antiboredom** [comment]
Hey all - glad it's working for you. As far as the compatibility issue goes I'm not sure what I think is best. It's definitely not great that it'll only work in the IDE but maybe this is ok? It also doesn't work if you have the "run in browser" option checked. Export is an option but I'm hesitant to include it since this would be the only use case right now.

@brysonian if you're going to be using this tomorrow do you need me to make a new release?

**Comment by brysonian** [comment]
@antiboredom no not yet, as long as we think it'll be a feature we can screen record against the zip up there, the class won't be online for a while so we will have time to think through all the details.

**Comment by lmccart** [comment]
yes, the mode with no setup/draw was discussed in this [thread](https://github.com/processing/p5.js/issues/158) and we decided against it because there didn't seem to be a good way to support this as well as instance mode.

**Comment by shiffman** [comment]
Ah, thanks for the reminder about the thread.  At the end @lmccart says:

>current plan is to support drawing without setup() and draw() in the IDE only. there will be functionality to publish from the IDE that modifies the code for deployment, wrapping everything in setup().

My feeling right now is to support it in the IDE (and possibly the web one too, cc @therewasaguy), but not support a separate export feature.  My gut is that we'll be ok.  Static mode would likely only be used at the very beginning of a class or workshop and by the time anyone is at the point where they might actually be working outside the IDE, the idea of static mode will be long forgotten.

All that said I've now realized that the problem here will be homework uploading.  If, say, a first class uses static mode and then the uploaded homework doesn't run (without an "export") that's not good.  So actually I wonder if it's just something to support only in the web IDE?

I've totally confused myself.  It seems like it was an easy switch for @antiboredom to turn on so maybe we leave it in for now and see what happens?

**Comment by brysonian** [comment]
I suppose the system into which the homework is uploaded could also do the wrapping, it does make things complicated though.

**Comment by antiboredom** [comment]
we've decided to not implement this for the time being! Closing the issue but if anyone feels very strongly about adding this in the future please just let me know.
