### ISSUE TITLE
stroke() has no default value

### ISSUE THREAD

**Issue by polyrhythmatic** [processing/p5.js-editor#105]
Using the function 
`stroke()`
gives different results in Chrome 43.0.2357.132 when compared with p5 editor 0.3.2

In chrome it seems there is a default value whereas in the editor I receive the error

`Uncaught Error: [object Arguments]is not a valid color representation.`

Using a value 
`stroke(255)`
eliminates this error.

Perhaps this is an issue with p5 - I am not sure the intended design of stroke. Should there be a default value? In processing stroke() requires a value.

**Comment by antiboredom** [comment]
I'm getting the same error in chrome - can you duplicate this?

**Comment by antiboredom** [comment]
I think this is an issue with p5 and not the editor. Closing for now but if anyone else comes across the problem please let me know and I'll re-open.

**Comment by justintspencer** [comment]
I got this same error when I tried to run the fill function w/o an argument

`fill();
9846: Uncaught Error: [object Arguments]is not a valid color representation.

Once I passed an argument to the fill function the error disappeared.

**Comment by lmccart** [comment]
yes, there's no default value, you have to put something inside to specify a fill color. see this page for possibilities.
http://p5js.org/reference/#p5/fill
