### ISSUE TITLE
Leak in nwhelper

### ISSUE THREAD

**Issue by brysonian** [processing/p5.js-editor#110]
I'm seeing a steady increase in resource usage every time I hit run. This might be related to this nw issue: https://github.com/nwjs/nw.js/issues/2372

**Comment by bmoren** [comment]
I've seen this a number of times to the point of running out of system memory recently. Ive also seen this happen to at least 3 of my students while drawing only simple 2d primitives. Just thought I should add a confirmation.

**Comment by antiboredom** [comment]
Thanks guys I'll take a look.

**Comment by antiboredom** [comment]
@brysonian @bmoren can you try this build and let me know if there are any improvements? http://saaaam.s3.amazonaws.com/p5-0.5beta.zip

If not, can you send me your system info and a sample sketch that causes the issue? Thanks!

**Comment by bmoren** [comment]
I'll give it a spin!

**Comment by antiboredom** [comment]
@bmoren are you noticing any improvements?

**Comment by bmoren** [comment]
Yes! Immediately. It noticeably hangs less when hitting the play button to run the sketch as well. One of my students has been testing as well, I should have his report on Tuesday 

Ben Moren
http://benmoren.com

**Comment by brysonian** [comment]
Yeah i've been running it here and it is much better!

**Comment by antiboredom** [comment]
Great - thank you for testing!
