### ISSUE TITLE
CoffeeScript support

### ISSUE THREAD

**Issue by baku89** [processing/p5.js-editor#122]
Thanks a lot for making this useful tools :+1: 
Is there a plan for supporting CoffeeScript?

**Comment by antiboredom** [comment]
Not currently, but I'm not opposed to it!

**Comment by sepans** [comment]
Don't know how transpilers integrate with Ace but it is interesting to try it out especially with Babel for ES6. I can take a look (iff you merge my previous PR @antiboredom ;)

**Comment by antiboredom** [comment]
It would definitely open up some interesting possibilities although we'd have to completely change the way we deal with previewing projects. @sepans is your PR ready? So sorry thought you were still working on it!!

**Comment by baku89** [comment]
Thanks for discussing my issue. I might not help you in coding but I'll enjoy beta testing if needed :smile:

**Comment by awt2542** [comment]
+1 for CoffeeScript support! :)

**Comment by lmccart** [comment]
there are no plans for coffeescript support right now, we are focusing on fixing issues with existing editor
