### ISSUE TITLE
some video formats don't play using the video tag

### ISSUE THREAD

**Issue by antiboredom** [processing/p5.js-editor#13]
@lmccart can you take a look at this and let me know what you think?

https://github.com/rogerwang/node-webkit/wiki/Using-MP3-&-MP4-(H.264)-using-the--video--&--audio--tags.

**Comment by sepans** [comment]
@antiboredom, I guess editor license needs to be changed to GPL, which is fine since it is very unlikely that anybody wants to build a commercial product based p5.js editor (no offense, the editor is so amazing there is no need for such thing ;)

**Comment by antiboredom** [comment]
@sepans GPL is totally fine with me!
