### ISSUE TITLE
drag onto dock

### ISSUE THREAD

**Issue by antiboredom** [processing/p5.js-editor#131]
dragging a file or folder on the dock icon should open a project

**Comment by shiffman** [comment]
I'm not able to get dragging a folder to work.  Is this expected to work or is there an OS limitation? (I may be missing something.)  Holding off on re-opening.

**Comment by antiboredom** [comment]
Oh yeah - still working on that bit - should have something soon!

**Comment by antiboredom** [comment]
should be fixed now - will make a new build soon...
