### ISSUE TITLE
Press Play opens Print dialog

### ISSUE THREAD

**Issue by p5k12** [processing/p5.js-editor#134]
This is a p5js issue and not an editor one.  Even when I use Sublime & Chrome, I'm getting this behavior.  
```
var periodsRows;
function preload(){
  periodsRows = loadStrings('assets/periods.txt');
}

print(periodsRows);
```
When I run this, a print dialog box opens up.  When I comment out the `print` line, it does not.

**Comment by antiboredom** [comment]
wow! that's really crazy. can you duplicate this?

**Comment by antiboredom** [comment]
Ah! I see. Can you file a bug for this over on the p5.js repo?

**Comment by Pastyguy** [comment]
Img getting the same result when i run this part of my code
function preload() {
	img = loadImage("assets/shark.jpg");
}
