### ISSUE TITLE
The new version says "A newer version P5 is available. Do you want to dwonload it?" (p5-win)

### ISSUE THREAD

**Issue by KouichiMatsuda** [processing/p5.js-editor#137]
Maybe a bug.
I tried to download it three times but it always shows the same message.
Is there any way to check the version number of the editor?
p.s.
  The new editor? sometimes creates an infinite sketch.js holder.

**Comment by antiboredom** [comment]
hmmm. Can you try downloading the new version directly from the releases page and let me know if the message is still popping up? https://github.com/processing/p5.js-editor/releases/tag/v0.5.0

**Comment by shiffman** [comment]
I'm experiencing this as well FYI.  I'm at ITP @antiboredom if it helps you to take a look in person.

**Comment by shiffman** [comment]
Sorry, mac 10.10.4

**Comment by antiboredom** [comment]
Ok thanks ! I'm it it!

**Comment by bmoren** [comment]
version 0.5.0 is listed as version 0.4.0 under the about menu.

**Comment by antiboredom** [comment]
Sorry about this guys I believe it should be fixed now (you'll need to re-download the latest release however).

In either case I'm going to add a new issue about making the update dialog not appearing each time.

**Comment by shiffman** [comment]
I can confirm this is fixed for me!
