### ISSUE TITLE
windows 32-bit build

### ISSUE THREAD

**Issue by Echo1234** [processing/p5.js-editor#143]
I just downloaded the p5.js editor for windows and everything went smoothly but when I tried running it i got this message: "This app can't run on your pc". I'm using the Windows 8 operating system. What might be causing this to happen? Thanks in advance.

**Comment by antiboredom** [comment]
Do you happen to know if you're running windows 32-bit or 64-bit?

**Comment by p5k12** [comment]
Hi,

Runs fine for me on Windows 8.

8.1 Enterprise
x64
i5-3230M
8G RAM

ms

**Comment by Echo1234** [comment]
I'm running windows 32-bit. Is that the problem?

**Comment by antiboredom** [comment]
@echo1234 that's probably the problem. I'll make you a 32-bit build tomorrow and hopefully it'll work on your system.

**Comment by Echo1234** [comment]
Thanks a lot. I would really appreciate that.

**Comment by Echo1234** [comment]
So what's the update on the 32-bit build? It's alright if you didn't have any time to make it.

**Comment by antiboredom** [comment]
hi @Echo1234 - try this, and let me know if it works: http://saaaam.s3.amazonaws.com/p5-5.1-win32.zip

**Comment by Echo1234** [comment]
Hello @antiboredom , the download seems to stop at 0.1 MB every time i try to download it. I'll reply again when i get it to work. By the way, thank you very much for taking the time to make it.

**Comment by Echo1234** [comment]
I just finished downloading it and it worked PERFECTLY! THANK YOU! You've really helped me out and man I can't thank you enough. You've really made my day mate. Thanks again.

**Comment by sparky64567** [comment]
works for me too - except for the play button... play button makes it hang up....

**Comment by dariox2** [comment]
Run fine here, including play button.  Windows XP 32 SP3.

**Comment by dariox2** [comment]
Run fine here, including play button.  Windows XP 32 SP3. Thanks!

**Comment by dariox2** [comment]
Run fine here, including play button.  Windows XP 32 SP3. Thanks!

**Comment by Paul1337** [comment]
Will be there an updated build?
