### ISSUE TITLE
errors while running in editor window (related to socket.io?)

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-editor#144]
The problem seems to be that occasionally the editor will throw up a whole lot of errors when using the built-in window. The best solution seems to be to restart or to choose the "run in browser" option.

![1](https://cloud.githubusercontent.com/assets/191056/9724265/86b08f00-55a2-11e5-96e6-506c94171de9.png)

Attaching some student comments in case they are helpful:

"I found that when I created a new project while another was already open, the program would also give crazy error messages, but when I closed the application, started it again and worked directly in the sketch window that opened automatically, it worked fine, even with the same (cut and pasted) code..."

"I came across the same problem yesterday. I click the settings button and then click the "run in browser" button. It works running in Chrome browser with the same sketch code. But still could not run in the builtin browser."

"For the record, I had the same problem a few days ago, and had to restart and copy paste the code into a new sketch to get it working again."

**Comment by antiboredom** [comment]
I've just moved this from socket.io to using postMessage.
