### ISSUE TITLE
Save file vs. Save project

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-editor#145]
I noticed today confusion around save file as vs. save project as.   A drastic measure might be to remove "save file as" entirely and only keep "save" and "save as" for the entire project.  This has the benefit of simplicity, but perhaps "save file as" is important for a reason I'm missing?  What's a user scenario for "save file as"?

(Related to this, if a user does not have the sidebar viewable and performs "save file as", the new file disappears behind the scenes.  Any new files created through "add file" or "save file as" should appear as tabs I believe.)

**Comment by shiffman** [comment]
@antiboredom went over this a few times and have decided to (for now) remove save file as and "save project as" will become "save as."  Speak now if you have any comments.

**Comment by lmccart** [comment]
:+1:
