### ISSUE TITLE
browser window not sized properly

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-editor#146]
I am not seeing this on my main machine, but on an ITP classroom laptop and a student's computer (both macs running 0.5.1), I am seeing the browser window sized too small with scrollbars, i.e.

![screen shot 2015-09-08 at 2 54 35 pm](https://cloud.githubusercontent.com/assets/191758/9744432/c2e2dc02-5639-11e5-9adb-68ae46b48d91.png)

```javascript
function setup() {
  createCanvas(500,400);
}

function draw() {
  background(0); 
}
```

**Comment by shiffman** [comment]
This is due to having "Show scroll bars" set to "Always" in Mac OS X System Preferences --> General.  @antiboredom is going to try increasing by a pixel or two and see if it helps, otherwise it's probably a documentation issue we need to think about.

<img width="529" alt="screen shot 2015-09-08 at 3 31 59 pm" src="https://cloud.githubusercontent.com/assets/191758/9745297/da807310-563e-11e5-8f39-711210de62a6.png">

The setting to make it go away is either of the other two options.

**Comment by lmccart** [comment]
can we build hidden scrollbars into the style in the default html? similar to `body{margin:0; padding:0}`? I may not know what I'm talking about!

**Comment by antiboredom** [comment]
Tried that very quickly with overflow: hidden but it disabled scrolling completely. I think there's another css way to do it - will look into it.

**Comment by antiboredom** [comment]
OK - looked into this a bit more - here's the deal. The canvas element has a default styled of `display:inline; vertical-align: baseline` which is what is actually causing the scrollbar to appear. We have three css options to fix this (there are probably others as well, but all three of these seem to do the trick):

1. Hide all scrollbars on the body `body::-webkit-scrollbar { display: none; }`
2. Make canvas elements `display:block`
3. Make canvas elements `vertical-align: top`

Number three seems least bad to me. Thoughts?

**Comment by lmccart** [comment]
hm. gut instinct, i'm most in favor of #1. because it leaves the default flow and layout of the elements intact as we claim to do with the p5.js library.

**Comment by lmccart** [comment]
on the other hand, it seems like a user might expect or want scrollbars.

i do think if they weren't showing up the first place they might look is in the html file and the scrollbar style line is pretty clear, so they could easily remove it.

i think either 1 or 2 would be fine.

**Comment by shiffman** [comment]
I think we ultimately want users to be able to move the canvas element around (as many examples do) so I am inclined to go with option 1.  I'm not 100% sure any of this is necessary though since we are just mirroring the actual OS behavior and it's fixable with the preferences.   Maybe we try 1 and see how it feels or we hold off on this and wait for more testing and see how often it comes up?

**Comment by antiboredom** [comment]
The problem with option 1 is that the scrollbars will always be hidden no matter what (including when you are scrolling, which is different than the default os behavior). The problem with 2 is that it changes canvas to a block element which totally changes document flow. And here's what option 3 would alter:
![image](https://cloud.githubusercontent.com/assets/344861/9747511/f77a3886-564b-11e5-9236-d30e73e99df0.png)

Also, this affects windows as well...

**Comment by shiffman** [comment]
I see that you added a solution into the recent release and I like it.  It feels ok to not see the scrollbars in the IDE since it feels like something a little different than a browser (and scrolling is still possible).  However, while this should have been obvious, I only now noticed that once you take your sketch outside of the editor, the behavior is retained. . . which is maybe a problem?  Students uploading p5.js projects and wondering why the scrollbar is never visible?

**Comment by antiboredom** [comment]
Actually I ended up going with the vertical-align option so it shouldn't hide scroll bars in the browser...

**Comment by shiffman** [comment]
Got it, sorry, I must have had that in my `index.html` from when we were testing and I kept "saving as" for new projects. . . apologies.
