### ISSUE TITLE
Save as inside existing project = infinite subfolders

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-editor#151]
1. Create a project called "something1"
2. Save as "something2" inside the "something1" directory.

See a magical infinite set of subdirectories.

![screen shot 2015-09-11 at 3 00 20 pm](https://cloud.githubusercontent.com/assets/191758/9823719/174ae614-5896-11e5-96be-bc9609c7c4da.png)

It works fine if you move out of the current existing directory.

**Comment by antiboredom** [comment]
Hahahah amazing

**Comment by antiboredom** [comment]
Ok, next release will prevent users from "saving as" a project into it's own directory.
