### ISSUE TITLE
prevent === warning message

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-editor#152]
Can we prevent the "Use `===` to compare" warning from happening? I could see this being confusing to students if we are teaching them just to use `==`.

![screen shot 2015-09-11 at 4 15 38 pm](https://cloud.githubusercontent.com/assets/191056/9825315/6b48f346-58a0-11e5-9957-9280905249bd.png)

**Comment by antiboredom** [comment]
Sure! Do you think we should get rid of warnings altogether?

**Comment by lmccart** [comment]
yeah after seeing some of the other things that get flagged, let's just remove them completely.

**Comment by kadamwhite** [comment]
Could these be something that could be enabled, rather than opted-out entirely?

**Comment by lmccart** [comment]
temporary fix, color the background white.
ideally, eventually, we can have a user preferences file to customize settings further.
