### ISSUE TITLE
Program won't quit with an Untitled/Unsaved project

### ISSUE THREAD

**Issue by evejweinberg** [processing/p5.js-editor#153]
Tried to quit (and discard this untitled doc) but get prompted 'Quit and Lose changes?', then I click 'Ok' but the program will not close until I save the doc as something. I got caught in a loop where I clicked 'Ok' and was prompted again, until I finally had to save the document to quit the program.

![screen shot 2015-09-12 at 10 49 05 pm](https://cloud.githubusercontent.com/assets/4630497/9834965/a4398e30-59a0-11e5-88bf-2cb2aa667368.png)

**Comment by antiboredom** [comment]
Thanks! I'll look into it.
