### ISSUE TITLE
Recursion Example in environment should be named "Functions"

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-editor#157]
reposting @pippinbar's issue on the p5.js repo:

"The Recursion Example in the downloadable environment (v0.5.2) is an example of using function calls to repeat work, rather than recursion. This example does not seem to appear on the website.

I don't know if this is overly picky, but it might confuse some learners about the nature of recursion (I'm teaching a course that involves some introductory programming)."

the title should be "functions" to match the example on the website
http://p5js.org/examples/examples/Structure_Functions.php

**Comment by lmccart** [comment]
looks like it would be helpful to just do a new pull of the examples from the site. this issue is also related: https://github.com/processing/p5.js/issues/924

**Comment by antiboredom** [comment]
@lmccart hey - so we're pulling from this file to get those structure examples: https://api.github.com/repos/processing/p5.js-website/contents/examples/examples_src/00_Structure?ref=master

It looks like it references both a recursion and function example. Can you remove the recursion example?

**Comment by lmccart** [comment]
doh. fixed, put up a _real_ recursion example: http://p5js.org/examples/examples/Structure_Recursion.php
