### ISSUE TITLE
save as?

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-editor#16]
Current behavior: ⇧⌘S is "saves file as" whereas I am used to ⇧⌘S to mean "saves project as".  Tiny issue and am not sure what others expect.  Just opening it for discussion.

**Comment by antiboredom** [comment]
save project as is now fixed - open to changing around the keyboard shortcuts. Anyone else have any thoughts?

**Comment by lmccart** [comment]
For organizational purposes, I'm closing this and adding the note about keyboard shortcut to other "save as" issue #182.
