### ISSUE TITLE
files have been modified outside the editor messages

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-editor#163]
Apologies in advance for making such a vague issue post.  I'm hoping to be able to pinpoint this more precisely and add more information here.   I'm starting this thread just to note that over the last couple days I've seen with students the (paraphrasing)  "files have been modified, you will lose your changes, ok or cancel" alerts often.  I believe that these are occurring erroneously though, again, I don't have a good way to reproduce the message (yet).   

All of the instances are with 0.5.2 on Mac OS X.

Anyone else seeing this?

**Comment by lmccart** [comment]
I see this message if I open the same project more than once and edit one (as expected). Have you seen it happen in an unexpected case or do you think students might just be getting confused and reopening the same project in another p5 window?

**Comment by shiffman** [comment]
It could be that, yes.   Though it would be nice for the editor not to allow the same project opened twice?  My suspicion is something going on when media assets are moving in and out of the directory?

I will do some further testing and try to report back more specifics.

**Comment by antiboredom** [comment]
Think I fixed this! Will be included in the next release.
