### ISSUE TITLE
White line under console area

### ISSUE THREAD

**Issue by jamesjgrady** [processing/p5.js-editor#164]
When resizing the window a white line appears at the bottom of the window.

![screen shot 2015-09-30 at 10 53 58 am](https://cloud.githubusercontent.com/assets/2600893/10196936/5b1b3598-6763-11e5-9539-2e42c5b59b56.png)

**Comment by benfry** [comment]
Moved here https://github.com/processing/processing/issues/3919, sorry for the noise.
