### ISSUE TITLE
How to import a library like original Processing IDE?

### ISSUE THREAD

**Issue by vinjn** [processing/p5.js-editor#179]

**Comment by knotech** [comment]
Hi @vinjn. Have you tried opening the index.html in the project and adding a 
`<script src='/path/to/the/library.js'>` ?

I would try either:
1. Copying the library.js into the folder of your project and setting the path from there.
2. Or if you want to pull it from a CDN, go to the preferences pane, and toggle the 'Run In Browser' option, and adding the `<script src='https://your.CDN.com/library.js'>` to the index.html file in the project.

**Comment by vinjn** [comment]
Thanks. @knotech 
Closing.
