### ISSUE TITLE
Alpha Error when working with HSB

### ISSUE THREAD

**Issue by sunwangshu** [processing/p5.js-editor#184]
When you set colorMode(HSB) and set a color like stroke(360,100,100,0.1), the fourth parameter 0.1 works well as the alpha value.

The issue is that when you try to access a value called stroke(360,100,100,0), then the color appear to have no transparency at all, which means alpha = 1, and the color appear the same as (360, 100, 100, 1). 

I think normally with alpha = 0 it means there be some 100% transparency and no color at all.

**Comment by lmccart** [comment]
this is fixed in the latest.
