### ISSUE TITLE
La versión actual de p5.js para windows no es compatible para windows 10

### ISSUE THREAD

**Issue by edwins04** [processing/p5.js-editor#188]
He intentado descargar p5 editor version 0.5.2 para windows, pero al ejecutarla en mi portátil me dice que esa versión no es compatible seria bueno que arreglaran ese inconveniente

**Comment by lmccart** [comment]
gracias. este es un duplicado de #185, voy a cerrarlo para organizar.
lo siento, no hablo bien español... :\
