### ISSUE TITLE
Support for real-time, collaborative, direct manipulation design process

### ISSUE THREAD

**Issue by brylie** [processing/p5.js-editor#189]
# User story
```
As a student
I need 'a personal dynamic medium' to express my thoughts
so I gain immediate and intuitive understanding of complex ideas
```

```
As a person communicating through rich, interactive media
I would like to directly manipulate my narrative expression without switching context
so that I can create at the speed of thought without having to think, much, like a computer
```
## Principle
<a href="https://youtu.be/PA139CERNbc?list=PL37ZVnwpeshH37NxpV6XbgdDpY-w48hMd&t=780"><quote>
Humans should human
computers should computer
and computers only exist so we can better human
</quote></a>

# Challenge
Even though the programming environment minimises time-to-comprehension by quickly rendering results when the play button is pressed, there is still significant separation between the visual output and the generative commands. 

The challenge is to **work together** to build a toolkit that provides nearly real-time responsiveness, [intuitive interaction](https://youtu.be/EzHsLt9vLbk?t=1651), and feedback between system components while [avoiding syntax errors](https://youtu.be/H4sSldXv_S4?t=422).

There are several projects in the same vein, or design space, that are working separately on seemingly different problems. The opportunity here is to combine forces to fill out the picture of a cohesive, visual, direct manipulation interface for creating non-linear, hypermedia narratives.

# Feature
Allow end-users to [directly interact](https://en.wikipedia.org/wiki/Direct_manipulation_interface) with geometric primitives, DOM elements, and other P5.js objects, and each other in real-time. People can set parameters on objects from one another, run arbitrary expressions in object parameters, [drop 'block' elements on to the canvas](https://youtu.be/H4sSldXv_S4?t=1178), and compose interactive objects that change scene [data flow](http://noflojs.org/).

## Environment
The environment is the container. It can contain information about the state of the exploration, global events, etc. It is the master document into which sub-documents are added and linked, in arbitrary combination. The environment is

> a general window that view[s] a large virtual world 
> 
> -- Alan Kay [describing](http://worrydream.com/EarlyHistoryOfSmalltalk/) the [Sketchpad User Interface](https://en.wikipedia.org/wiki/Sketchpad)

The environment is, in effect, any [modern web browser](https://html5test.com/results/desktop.html).

## Stages / Scenes
Scenes are arranged within the environment, and within one another. They contain elements, both visible and invisible. Scenes and their elements can change over time.

> ![Godot scene graph](http://www.godotengine.org/attachments/100/download)
>
> Source: [Godot engine scene diagram](http://www.godotengine.org/projects/godot-engine)

### Linking
Scenes can be linked to one another, in any order.
![Twine flow diagram interface](http://twinery.org/img/twine2-storymap-thumb.png)

## Actors / Elements
Elements are like the actors in the scene. They have properties and behaviours that make up their personalities. They interact, sometimes badly, with one another.

### Shapes
Complex shapes can be made of simple [shapes](http://p5js.org/reference/#group-Shape). People like to work with things directly, so may like to work directly with the shapes.

People can select basic shapes from a palette, drag them on to the stage, and modify their properties.

![inkscript-shapes](https://cloud.githubusercontent.com/assets/17307/11145793/6738d396-8a11-11e5-9822-f2c398e6421f.png)

### Multimedia
There are also sound, image, video, and three dimensional elements, as well as lights and cameras.

## Flow and rules
Ideas can move throughout the system very quickly. While data and events are moving around, they get modified and cause reactions. Stage objects, and stages themselves share and modify data streams.

> ![Tensor Flow diagram](http://www.tensorflow.org/images/tensors_flowing.gif)
>
> Source: [TensorFlow](http://www.tensorflow.org/)

### Programming
Within flow elements, step-wise programs can be built with visual blocks, or some other iconic representation. This visual/iconic grammar is accessible to adults and children alike:

> the directly symbolic approach taken by [many languages] would be difficult for the kids to process since evidence existed that the symbolic stage (or mentality) was just starting to switch on. In fact, all of the educators that I admired (including Montessori, Holt, and Suzuki) all seemed to call for a more figurative, more iconic approach.
>
> Alan C. Kay - [The Early History of Smalltalk](http://worrydream.com/EarlyHistoryOfSmalltalk/)

> ![PureData flow interface](https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Pdobjects.svg/500px-Pdobjects.svg.png)
> 
> Source: Wikipedia - [PureData](https://en.wikipedia.org/wiki/Pure_Data)

#### Declarative language/reasoning
Humans are very good at declaring things. "I'm hungry", "put the groceries on the table", "I wish my flowers would grow"... Computers need to understand declarative statements, so that humans can tell them what to do.

With regards to a rich media environment, we need a declarative language to create multi-dimensional, interactive media.

> [Declarative 3D for the web will] allow anyone to easily create, share, and experience interactive 3D graphics - with possibly wide ranging effects similar to those caused by the broad availability of video on the Web.
>
> Source: [Declarative 3D for the Web Architecture Community Group](https://www.w3.org/community/declarative3d/)

#### Blocks
Programming elements can be arranged and snapped together, or connected in a flow graph:

> ![MIT Scratch block interface](https://upload.wikimedia.org/wikipedia/en/7/78/Scratch_Hello_World.png)
> 
> Source: Wikipedia - [Scratch (programming language)](https://en.wikipedia.org/wiki/Scratch_%28programming_language%29)

#### Containers
Programming logic is contained in, or associated with, canvas elements:
![squeak eToysUI](https://upload.wikimedia.org/wikipedia/commons/d/df/Squeak-screenshot.png)

### Encapsulation, Abstraction
Blocks can be combined into 'meta' blocks, which abstract the inner workings for visual simplicity. Visual programs may be encapsulated into self-contained elements. These elements may send and receive data streams through external interfaces:

> ![Cameleon language](http://www.shinoe.org/cameleon/img/Sans-titre2.jpg)
>
> Source: [Cameleon language: Features](http://www.shinoe.org/cameleon/features.html)

### Modularity
Creations can take external input and provide output that can be accessed by other creations. This modular approach allows the entire space of design possibilities to communicate and resonate.

### Rendered output at each stage
Each programming element can display the current 'state' of processed data. This helps the user to understand changes in each step of the programming flow:

> ![Blender 3D node-based editor](https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Working_with_Nodes_Blender.PNG/640px-Working_with_Nodes_Blender.PNG)
>
> Source: Wikipedia - [Working with nodes in Blender 3D](https://en.wikipedia.org/wiki/Blender_%28software%29)

Rendered output can include visual, numeric, text, and audio representations.

### Context
Elements interact with one another, communicate, and change their surroundings. This form of context-full interaction enables rich, and emergent behaviour.

> With native methods, we operate on context ... we operate on objects — instantiate them, change their properties, and add them to canvas. You can see that these objects are first-class citizens...
>
> Source: [Introduction to Fabric](http://fabricjs.com/fabric-intro-part-1/)

### Delayed
People may wish to share their work with others. To enable sharing and remixing, allow makers to publish their work to a public repository. 

Publishing and remixing has been demonstrated by many community projects, including [Khan Academy](https://www.khanacademy.org/computing/computer-programming/browse), [Scratch](https://scratch.mit.edu/explore/?date=this_month), [D3 Building Blocks](http://blockbuilder.org/), and [eToys](http://www.squeakland.org/showcase/everyone/).

### Real-time
In addition to sharing work for later reuse, people may wish to collaborate in real-time. To this end, the tool should support concurrent interaction with the project space. It should also indicate presence and enable communication, so that collaborators can interact with one another as well as the project.

### Massively multiplayer
Makers can share and remix resources in a virtual space, i.e 'metaverse'. Collaborators can make open-access or protected creations.

> ![Voxelands photo](http://www.voxelands.com/images/background.jpg)
>
> Source: [Voxelands: the fun-focused Free Software voxel world game](http://www.voxelands.com/)

## Platform
The platform should be built of Web Platform technologies.

## Output
The final output of a project will be standard Web Platform technologies. The output should primarily target web browsers, or other environments that render native Web Platform code.

### WebGL
One output option is WebGL. WebGL has the following benefits:

> *  works in browsers without installing additional software (plugins)
> *  crossplatform, intended for all desktop and embedded systems
> *  open standard, does not require licensing fees
> *  supported by the leading participants of the IT market (Google, Apple, Microsoft, Nvidia, Samsung, Adobe and others)
> *  based on OpenGL which is familiar to developers
> *  can be integrated with other browser technologies
>
> Source: Blend4Web User Manual - [Advantages of WebGL](https://www.blend4web.com/doc/en/about.html#about-webgl-benefits)

# Reference
There are several emerging projects and tools that allow direct manipulation of graphic and program objects. This section contains a few demonstrations and tools.

## Presentations
* Mira Dontcheva - [Lowering the Barriers to Learning Complex Visual Design Tools](https://www.youtube.com/watch?v=vIHkGQxuBtc)
* Pamela Fox (@pamelafox) - [Creating Interactive Learning Interfaces at Khan Academy](https://www.youtube.com/watch?v=EzHsLt9vLbk&feature=youtu.be&t=27m08s)
* Jennifer Jacobs (@pixelmaid) - [A demo of Para](https://www.youtube.com/watch?v=Tdvj8XMrqXc)
* Alan Kay - [A powerful idea about ideas](https://www.ted.com/talks/alan_kay_shares_a_powerful_idea_about_ideas)
* Scott Klemmer - [Direct Manipulation](https://www.youtube.com/watch?v=pSDPDLQ4r5k)
* John Resig (@jeresig) - [Using JavaScript to Teach JavaScript](https://www.youtube.com/watch?v=H4sSldXv_S4)
* Tom De Smedt (@tom-de-smedt) & Frederik De Bleser (@fdb) - [Agile Data Mining and Visualization](https://www.youtube.com/watch?v=0oUP7uHAsNA)
* Toby Schachman (@electronicwhisper) - [Apparatus: A Hybrid Graphics Editor / Programming Environment](https://www.youtube.com/watch?v=i3Xack9ufYk)
* Scott Snibbe (@snibbe) - [Direct Manipulation Animation](https://www.youtube.com/watch?v=tHiSYe-PLIY)
  *  [Exploring the Universe Through Interactive Art](https://www.youtube.com/watch?v=0fxdEQsBP8k)
* Bret Victor (@worrydream) - [Media for Thinking the Unthinkable](http://worrydream.com/MediaForThinkingTheUnthinkable/)

## Tools
* CDG Labs [Apparatus](https://github.com/cdglabs/apparatus) - a hybrid graphics editor / programming environment for creating interactive diagrams.
* [Blender3D](http://blender.org) - 3D modelling, animation, etc. Allows direct manipulation and programming through visual blocks and flow-based interface.
* [Caméléon](http://www.shinoe.org/cameleon/) - a graphical language for functional programming.
* [Godot](http://www.godotengine.org/projects/godot-engine) - multi-platform 2D and 3D game engine. Provides direct-manipulation of game assets, parameter editor, and scripting interface when needed.
* Khan Academy [live editor](https://github.com/Khan/live-editor) - gives learners an editor on the left (either ACE or our Blocks-based drag-and-drop editor) and an output on the right (either JS+ProcessingJS, HTML, or SQL).
* [Mozilla Together.js](https://togetherjs.com/) - real-time presence, communication, and collaboration.
* [NodeBox](https://www.nodebox.net/) - Cross-platform, node-based GUI for efficient data visualizations and generative design. Enabl[ing] designers to automate boring production challenges, visualize large sets of data and access the raw power of the computer without thinking in ones and zeroes.
* [Para Drawing](http://paradrawing.com/) - a digital illustration tool tool that uses direct manipulation to define and edit procedural artwork.
* [PureData](http://puredata.info/) - graphical, multimedia programming environment with built-in [support for real-time collaboration](https://en.wikipedia.org/wiki/FUDI)
* @ravichugh / [sketch-n-sketch](https://github.com/ravichugh/sketch-n-sketch) - allows users to freely mix between programmatic and direct manipulation.
* [Squeakland eToys](http://www.squeakland.org/) - a media-rich authoring environment and visual programming system
* [Twine.js](http://twinery.org) - open-source tool for telling interactive, nonlinear stories. 

## Articles
* Henri Bergius (@bergie) - [Direct manipulation interfaces](http://bergie.iki.fi/blog/direct_manipulation_interfaces/)
* Joel Brandt (@joelrbrandt), Philip J. Guo, Joel Lewenstein,  Scott R. Klemmer,  Mira Dontcheva - [Opportunistic Programming: Writing Code to Prototype, Ideate, and Discover](http://joelbrandt.org/publications/brandt_ieee2009_opportunistic_programming.pdf)

## Books
* [No Code Required](http://shop.oreilly.com/product/9780123815415.do) by Allen Cypher, Mira Dontcheva, Tessa Lau, Jeffrey Nichols

## Definitions

<dl>
<dt>Dataflow</dt>
<dd>Dataflow connect[s] computational actors into stages (pipelines) that can execute concurrently. --Wikipedia: <a href="https://en.wikipedia.org/wiki/Dataflow">Dataflow</a>
</dd>
<dt>Metaverse</dt>
<dd>A collective virtual shared space... made up of persistent, shared, 3D virtual spaces linked into a perceived virtual universe. --Wikipedia: <a href="https://en.wikipedia.org/wiki/Metaverse">Metaverse</a>
</dd>
<dt>Operational transform</dt>
<dd>[Method to] support a range of collaboration functionalities in advanced collaborative software systems. --Wikipedia: <a href="https://en.wikipedia.org/wiki/Operational_transformation">Operational transformation</a>
</dd>
</dl>

**Comment by mauriciovieira** [comment]
:+1:

**Comment by antiboredom** [comment]
This is super interesting - thanks for posting! I think this is a bit outside the scope of the p5 editor at the moment.

**Comment by brylie** [comment]
OK, thanks for your feedback. The main observation is that all of the projects have limited scope, but seem to be working on pieces of a bigger picture.
