### ISSUE TITLE
Error running empty-example sketch.js

### ISSUE THREAD

**Issue by leon-guiu** [processing/p5.js-editor#191]
p5* 0.5.6 IDE console blank when running empty-example sketch.js
![screen shot 2015-11-07 at 12 43 40](https://cloud.githubusercontent.com/assets/14298581/11017852/8ce0362c-85a5-11e5-97ef-2a13869bcfa8.png)
![screen shot 2015-11-07 at 14 47 00](https://cloud.githubusercontent.com/assets/14298581/11017853/9617d844-85a5-11e5-9f97-48984c041ba3.png)

**Comment by antiboredom** [comment]
@lmccart these are being pulled from another repo - could you take a look?

**Comment by lmccart** [comment]
yes it's because of the paths, related to this: https://github.com/processing/p5.js/issues/1012.
the empty example in the next release will match the default file structure for p5 editor.
