### ISSUE TITLE
Error when trying to draw a simple shape outside of setup or draw functions

### ISSUE THREAD

**Issue by geoffalday** [processing/p5.js-editor#192]
It looks like trying to draw a simple shape outside of the setup() or draw() functions causes an error (see attached). This works fine when placed in those functions. I realize it's not a best practice to structure sketches like this but wanted to let you know. I found this while working through the new P5.js course on Kadenze. Thanks!

![p5-error-ellipse](https://cloud.githubusercontent.com/assets/713227/11045564/c5e461a2-86ed-11e5-8888-5d2b59f8179d.png)

**Comment by antiboredom** [comment]
Thanks for posting. This is actually just part of p5 - the functions only work within setup and draw (or functions that are called from within setup and draw)

**Comment by geoffalday** [comment]
@antiboredom Thanks! Excited about this project.
