### ISSUE TITLE
saveCanvas is creating screenShot with black background

### ISSUE THREAD

**Issue by DaRockJaeger** [processing/p5.js-editor#193]
Hello,

saveCanvas is creating a screenShot with a black background. When I render my sketch, the background is white.

Best regards

**Comment by lmccart** [comment]
hey @DaRockJaeger are you actually drawing the background as white (background(255)) or are you just using the default clear background?

**Comment by DaRockJaeger** [comment]
Hello,

i am using the default clear background.
When setting the bckground color manually to white again, everythign works.
Thank you :dancer:
