### ISSUE TITLE
translate(x, y) doesn't reset in windows

### ISSUE THREAD

**Issue by genekogan** [processing/p5.js-editor#211]
i taught a p5.js workshop a few days ago and a group of students using the windows version of the editor reported a bug in which (i think) translate(x,y) didn't reset automatically at the beginning of the next frame. i didn't get a chance to verify this so not sure it wasn't a bug their side, but if someone is using the editor on windows, might be good to check on this.

**Comment by lmccart** [comment]
this should be fixed with an update to the library:
https://github.com/processing/p5.js-editor/pull/209

@antiboredom do you have time soon to merge this in? or is it ok for me to go ahead and do it?

**Comment by lmccart** [comment]
sorry this took so long! this is fixed in 0.5.8.
