### ISSUE TITLE
newly designed editor(0.5.9) doesn't scroll far enough

### ISSUE THREAD

**Issue by hanswillem** [processing/p5.js-editor#216]
Hi,

For me the new editor (0.5.9) doesn't allow me to scroll to the end of the code. The last two or three lines of code are hidden behind the console panel. Is it me? I am on OSX 10.10.3

Grtz,
HW

**Comment by lmccart** [comment]
yes, it's our new initiative to encourage people to write more concise code.
but really, ack sorry, will post a fixed version soon.

**Comment by hanswillem** [comment]
:) 

Great! Like the new design btw!

Grtz,

**Comment by kursor** [comment]
Having same issue. Some kind of padding issue.
