### ISSUE TITLE
autocomplete codeing

### ISSUE THREAD

**Issue by kusha-b-k** [processing/p5.js-editor#222]
please integrate the autocomplete coding for the editor

**Comment by kusha-b-k** [comment]
autocomplete is missing

**Comment by lmccart** [comment]
thanks! this is covered here: https://github.com/processing/p5.js-editor/issues/94. so i will close this one for organizational purposes.

**Comment by kusha-b-k** [comment]
ohh ok sorry  i have not checked that issue number..
