### ISSUE TITLE
pinch to zoom 

### ISSUE THREAD

**Issue by kusha-b-k** [processing/p5.js-editor#224]
Include the pinch to zoom option in the code editor to increase the font size..

regards..

**Comment by lmccart** [comment]
hi @kusha-b-k, you can adjust the font size via the settings panel (click the gear wheel in the corner), or using the key command command-+. we unfortunately won't be able to support more options than that at this time.

**Comment by kusha-b-k** [comment]
yes i know that option,but if we provide this option it will become user friendly...

thanks

**Comment by lmccart** [comment]
i understand. however, we have a long list of things things that still need fixing. until we get most of those finished, we need to hold off on adding new functionality.

**Comment by kusha-b-k** [comment]
ok cool
