### ISSUE TITLE
editor, Linux: make i3/4/5/686 version, or at least label the download as x64

### ISSUE THREAD

**Issue by RAWRR** [processing/p5.js-editor#251]
Please compile for i386? I was unpleasantly surprised after the download that it wasn't the correct binary for my system :(

**Comment by fuzzySi** [comment]
Yes, could you confirm if it's 64 bit only?

**Comment by lmccart** [comment]
yes it is 64 bit only right now, i've updated the download page to indicate this https://github.com/processing/p5.js-website/commit/b7f299609c18c525a88a3e53e7d9c8463924c4f4

**Comment by davejm** [comment]
@lmccart the thing stopping me from creating a working 32 bit build is the ffmpeg library. So I should be able to make 32 bit builds but sounds won't work until those libraries are found/built which seems quite involved. This is a downside of nw.js compared to electron which has the right codec support out of the box.

**Comment by RAWRR** [comment]
I think Electron doesn't have 32bit support, in Windows at least. There's a larger problem here in that new toolkits/frameworks are nullifying 32bit out of the box and giving devs no choice.

Anyway 32bit isn't an XP issue, no one disagrees XP is a security sinkhole. Linux on the other hand produces current and maintained 32bit systems and they're valuable for the literally millions of 32bit machines still out there.
