### ISSUE TITLE
Does not run on xp.

### ISSUE THREAD

**Issue by Recarte** [processing/p5.js-editor#254]
Exe file does not run on windows xp.
I get an error message saying that p5.exe is not a valid win32 application.

**Comment by davejm** [comment]
Relates to issue #251. Currently the builds are for 64 bit machines. It should be easy to create 32 bit versions by adding the relevant packaging targets. I might look into fixing this. Whether the created 32bit binaries would work on Windows XP is another matter as I'm not sure it's supported.

**Comment by lmccart** [comment]
yeah XP is not supported, but it'd be good to add a 32 bit version. @davejm if you want to look into this, that'd be great.

**Comment by Recarte** [comment]
Understood, thanx.
