### ISSUE TITLE
Update the version of Vue.js to v1.0

### ISSUE THREAD

**Issue by kaorun343** [processing/p5.js-editor#260]
Hello.
I know that this project is using vue.js but the version of this is still v0.10.
There are many differences between v0.10 and v1.0, so it will be hard to rewrite the codes.
However, v1.0 gives us many nice features, for instance, v1.0 allow us to utilize "prop" so it makes the  stream of passing data clearly. For sustainable maintenance, I suggest you to update the version of Vue.js to v1.0.

**Comment by lmccart** [comment]
thanks, I agree it would make sense to update to 1.0. however, we are actually working on a new web editor and discontinuing support of the desktop editor once that is ready (in a couple months). so at this point, we will need to focus our energy on that project and not sink more into updating to vue 1.0.

**Comment by kaorun343** [comment]
I see, thanks for your answer :smile:
