### ISSUE TITLE
Can't run p5 editor on Windows 7

### ISSUE THREAD

**Issue by ktlqai** [processing/p5.js-editor#272]
Yes, I double-click p5.exe in extracted zip file of download but error dialog showed up saying this file is not compatible with your operating system type (32-bit or 64-bit).

Your download has no option to choose 32-bit or 64-bit for Windows. Mine OS is 32-bit Windows 7.

**Comment by davejm** [comment]
@ktlqai, this editor only has 64bit versions

**Comment by ktlqai** [comment]
@davejm , thank you, then!
