### ISSUE TITLE
Could you join efforts with processing-p5js-mode from Fathom Information Design?

### ISSUE THREAD

**Issue by q2dg** [processing/p5.js-editor#273]
Instead of having a separate IDE for P5.js, why not integrate P5.js as a new "mode" of standard Processing IDE like this project (https://github.com/fathominfo/processing-p5js-mode) does?
Thanks

**Comment by lmccart** [comment]
I'm a bit confused, there is already a p5.js mode for Processing.

**Comment by lmccart** [comment]
To give further background, we are actually planning to stop support of this editor once we launch the new web editor we've been focusing our development energy on. I see the p5.js mode for Processing as a good holdover or alternative until that is ready, but they are separate projects.

**Comment by q2dg** [comment]
My wish would be having one tool "to rule them all". One Processing IDE with "Java mode", "Android mode" and "Javascript/P5.js Mode" would be excellent: desktop, mobile and web all in one

**Comment by lmccart** [comment]
I understand. However, p5.js and Processing are separate projects. While we talk frequently about shared goals between them, we'd prefer not to merge them but to instead give each project the space to grow and develop independently and organically.
