### ISSUE TITLE
p5 editor and the print vs println issue

### ISSUE THREAD

**Issue by molleindustria** [processing/p5.js-editor#275]
It seems like the editor linked to the official site
https://p5js.org/download/

Still ships with an old version of p5.js that throws an error with print(). 
I understand the infamous println change has been reverted right?

**Comment by lmccart** [comment]
it has ;)
i'll post a new version with this change asap!

**Comment by lmccart** [comment]
just posted a new version (https://github.com/processing/p5.js-editor/commit/583090cccf020f4b84f7d4b78e8193f7559f6bf3)
