### ISSUE TITLE
Tab Indentation null

### ISSUE THREAD

**Issue by samarjeet27** [processing/p5.js-editor#30]
When I open a file, the file content shows ‘undefined’ instead of tab characters(\t) when the indentation amount is not set. The user should not be allowed to set a null value for Indentation Amount. If it’s null, a default value should be entered. See image below –

![image3](https://cloud.githubusercontent.com/assets/2987087/5302185/6c9dd0be-7c04-11e4-8c76-5c7a5cf484f3.png)

in another editor, it looks something like this
![image4](https://cloud.githubusercontent.com/assets/2987087/5302641/3b1dce1e-7c08-11e4-89d8-f0e5e6393517.png)

**Comment by antiboredom** [comment]
thanks!
