### ISSUE TITLE
Console Not Reporting Syntax Error

### ISSUE THREAD

**Issue by KaroAntonio** [processing/p5.js-editor#38]
Here is an example of an error not being reported in the console.
A simple syntax error is included in the draw function, effectively breaking the sketch and yet the console is happily blank, with nothing to report.

![console error miss](https://cloud.githubusercontent.com/assets/5997028/6653279/a7497944-ca50-11e4-9414-28c77d06f2bc.png)

**Comment by antiboredom** [comment]
this should be fixed now!

**Comment by KaroAntonio** [comment]
thanks!
