### ISSUE TITLE
Make menu items for various keyboard shortcuts

### ISSUE THREAD

**Issue by therewasaguy** [processing/p5.js-editor#50]
Watching people use the IDE, they did not notice the Settings gear icon, and were instead looking for Settings in the gui.menu. It would be good to either add all of the Settings as its own Menu, or to add Show/Hide settings to one of the existing menus (i.e. Window --> Show/Hide Preferences)

**Comment by antiboredom** [comment]
Agreed. We need menu items for:
* showing the preferences: command ,
* increasing and decreasing font size: command + and command -
* showing/hiding the sidebar: command b
* reformatting the code: command t

**Comment by antiboredom** [comment]
@Bruehausu can you take a look at adding the find and find-and-replace menu items when you get a chance?

**Comment by Bruehausu** [comment]
@antiboredom I'm not sure if I'm crazy, but I couldn't actually find the code for find & replace. If you know where the functions are, I'll add them straight away.

**Comment by antiboredom** [comment]
Oh - sorry this is just part of the ACE editor!

**Comment by Bruehausu** [comment]
ok I'm looking there right now, but I just realised: How are we currently letting people know about all of the other builtin ace functionality and the increment/decrement shortcuts (cmd + [, cmd + ]) defined in editor.js?

**Comment by antiboredom** [comment]
My thought is that we just add menu items for anything else built into ace that we want to expose to users.
