### ISSUE TITLE
new file can be created without an extension

### ISSUE THREAD

**Issue by pixelmaid** [processing/p5.js-editor#51]
Doing so throws a FILE_NOT_FOUND error, however the file is still created, and can be renamed with an extension.

should we enable people to create new files without extensions?  It seems likely that new users will not automatically know to add .js extensions to their filenames, and this could trip them up.

**Comment by andyinabox** [comment]
Seems like this is fixed? When I test this I'm getting a message that indicates the .js extension is added.

![screenshot 2015-06-23 17 55 25](https://cloud.githubusercontent.com/assets/151084/8318243/17173340-19d1-11e5-8adf-c45b1080769b.png)
