### ISSUE TITLE
Move from dedicated IDE to a set of atom packages or just create the packages as separate ideas??????? 

### ISSUE THREAD

**Issue by benhinchley** [processing/p5.js-editor#65]
Hey Guys, I really like the work you guys are doing on this and have been playing around with the editor a lot, as a way of starting and creating ideas, but I often find myself falling back to my editor of choice [atom.io](https://atom.io/) and in doing so have started to make some pretty rudimentary packages for atom, to help in my p5 development. I was wondering if instead of or in addition to, we(I or the community) create a series of packages for atom(and any other editor) that did similar things to this editor?? I have been working on a series of snippets/autocompletion features for the main parts of the library, though there is defiantly more that can be done. I warmed up to the idea (of extending atom) after seeing what Facebook are doing with the [nuclide project](http://nuclide.io/) in turning it into a fully feature dev environment for react and react native. What are your guys thoughts on this??

**Comment by antiboredom** [comment]
Hi - it would be great to build p5 packages for various editors like atom and sublime - excited to see what you come up with!

**Comment by benhinchley** [comment]
I am going to close this issue, though I am still working on the package just been a bit slow. will open this back up when I have released something
