### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by antiboredom** [processing/p5.js-editor#7]
We need to write up some credits - this will appear when users look at the "about" menu.

**Comment by nucliweb** [comment]
Hi @antiboredom, if you want, I work on this feature.

**Comment by antiboredom** [comment]
@nucliweb that would be great - thank you!

**Comment by nucliweb** [comment]
@antiboredom do you like the system of Brackets for show credits?

![About](https://s3-eu-west-1.amazonaws.com/nucliweb/P5js/About.gif)

**Comment by antiboredom** [comment]
@nucliweb I hadn't seen this before, but yeah I really like it!

**Comment by nucliweb** [comment]
Ok, I will work in this concept for the credits section ;)
