### ISSUE TITLE
Output window should maintain dimensions and location

### ISSUE THREAD

**Issue by antiboredom** [processing/p5.js-editor#72]
The output window should maintain its size and location when you run your sketch.

**Comment by shiffman** [comment]
Related to this, I'm not sure what the right behavior should be, but we should brainstorm "smart" ways of determining initial browser size upon first run.  Yesterday giving a workshop the browser window was so large it was slightly offscreen and I had trouble grabbing the corner to shrink it.

The sizing and placement of the editor and browser window are key for running multiple projects (esp. while teaching).

**Comment by antiboredom** [comment]
Agreed! Right now it's positioned relative to the source code window but there are no checks in place to make sure it doesn't go off screen etc.
