### ISSUE TITLE
images are opened as text files

### ISSUE THREAD

**Issue by molleindustria** [processing/p5.js-editor#78]
Loving the new IDE!
Yay glitch art
![screen shot 2015-05-31 at 7 13 39 am](https://cloud.githubusercontent.com/assets/12369651/7901728/98e82bb0-0764-11e5-91e2-e8c607ebe362.png)

Also accessing images should trigger new tabs.

**Comment by antiboredom** [comment]
Thanks! Note to contributors: we could use file extensions to determine if the file can be viewed in the editor, or something like this: https://github.com/bevry/istextorbinary

For now I think we should just disable viewing non-text files, but for the future I'd like the editor to preview images, videos and audio files.

**Comment by andyinabox** [comment]
Seems like this is fixed? I just pulled latest and it's giving me a prompt when I attempt to open an image file instead of opening it "Unsupported file type. Types we can edit: txt,html,css,js,json,scss,xml,csv,less"

**Comment by antiboredom** [comment]
yes! fixed now.
