### ISSUE TITLE
Duplicated tabs

### ISSUE THREAD

**Issue by molleindustria** [processing/p5.js-editor#79]
Clicking on a file in a folder in the left panel, closing the folder, and then clicking on the same file opens a duplicate of the same tab
![screen shot 2015-05-31 at 7 18 00 am](https://cloud.githubusercontent.com/assets/12369651/7901736/2a5cbbc4-0765-11e5-9724-bfab877ebedf.png)

**Comment by antiboredom** [comment]
it looks like there's a visual bug as well - with the scroll bar...

**Comment by antiboredom** [comment]
Hey @pixelmaid  - I noticed you assigned yourself to this a bit ago. Do you think you'll get a chance to take a look in the next few weeks? If not no worries at all - just wanted to check in.

**Comment by andyinabox** [comment]
I'm happy to take a look if @pixelmaid isn't able to!

**Comment by antiboredom** [comment]
hey @andyinabox - if you have some time, please do. thanks!
