### ISSUE TITLE
old sketch continues to be served on port 3000 

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-editor#83]
I can't full explain or pinpoint the steps to reproduce this (will follow up when I can), but I'm experiencing a problem where a sketch a ran when first working with the editor today continues to run even if I quit the editor, make a new project, etc.

![screenshot 2015-06-04 10 23 18](https://cloud.githubusercontent.com/assets/191758/7981004/eb1716f2-0aa3-11e5-8c13-bef5f075e71d.png)

The only way I can get something to run is to leave the above sketch open and run a new one (which is served on 3001).

![screenshot 2015-06-04 10 26 02](https://cloud.githubusercontent.com/assets/191758/7981035/1f73a0c8-0aa4-11e5-8274-b4062b750ccf.png)

**Comment by antiboredom** [comment]
I wonder if this is the same situation, or related to #68?

**Comment by shiffman** [comment]
Ah, after some poking around I believe this is the same bug.  Will close and can re-open if I notice something more/new after #68 is resolved.
