### ISSUE TITLE
editor fetches latest from GitHub master branch, should instead fetch latest Release

### ISSUE THREAD

**Issue by therewasaguy** [processing/p5.js-editor#89]
the editor fetches the latest version of libraries (p5.js, p5.sound.js, p5.dom.js) direct from the master branch of https://github.com/processing/p5.js, but should probably fetch from the official releases instead which we assume are stable. https://github.com/processing/p5.js/releases

**Comment by antiboredom** [comment]
the same is happening whenever users run the editor. I did this because p5 was changing so rapidly, but now I wonder if we should be more deliberate about it?
