### ISSUE TITLE
println and console.log don't work with numbers

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-editor#91]
Perhaps related to what we decide about #80:

I'm only seeing output of `println()` or `console.log()` in the browser console, not in the IDE message console.  I believe it should be there?

**Comment by antiboredom** [comment]
This must be a regression - will look into it.

**Comment by antiboredom** [comment]
I'm not able to reproduce this - @shiffman can you post the code you were running?

**Comment by shiffman** [comment]
This is my test code:

```
function setup() {
  createCanvas(100,100);
}

function draw() {
  println(frameCount);
}
```

I am running 0.3.0 on Mac OS X 10.10.3.  

![screen shot 2015-06-13 at 10 55 07 pm](https://cloud.githubusercontent.com/assets/191758/8146115/48cf43fa-121f-11e5-8d34-21c9dc6ca602.png)

Strange!  No one else seeing this?

**Comment by antiboredom** [comment]
Ah! Ok - able to reproduce now. This seems to happen if you pass it a number (strings and objects appear to work fine). Will fix!

**Comment by sepans** [comment]
Most likely not related. But I remember the core team added [this](https://github.com/processing/p5.js/blob/master/lib/p5.js#L3926) <code>JSON.parse(JSON.stringify())</code> to have printed items appear in order. Could it be related?

**Comment by workergnome** [comment]
Yeah, did a bit of checking.  Doesn't look related to the terrible JSON hack.
